version: "3"

volumes:
    db-data:

services:
    db:
        image: postgres:14 # CockroachDB cluster might be a better fit for production deployment
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
